update `renv.lock` to use latest pkg versions as of 3/1
Biogen-Inc/tidyCDISC pull request #204
Opened 2023-03-09 13:29 UTC by AARON-CLARK

Didn't update R version though. Probably should.

2023-03-09 18:38 UTC, AARON-CLARK commented
Per discussion on 3/8: will likely move forward with solution that updates `renv.lock` prior to each release. Need to add this step to 'Cutting a new release' wiki.

2023-03-10 20:14 UTC, Jeff-Thompson12 requested changes
It appears if you run `renv::init(bioconductor = FALSE)` that it will remove the weird Bioconductor dependency we have.

2023-03-10 20:34 UTC, AARON-CLARK commented
Thanks @Jeff-Thompson12, updated with commit [4427f75](https://github.com/Biogen-Inc/tidyCDISC/pull/204/commits/4427f75533497d83af3bf4a6889ece8c0e0a9392).

2023-03-10 20:52 UTC, Jeff-Thompson12 approved these changes
LGTM! @AARON-CLARK do you want anyone else to weigh in or am I good to merge?

2023-03-10 20:53 UTC, AARON-CLARK commented
> LGTM! @AARON-CLARK do you want anyone else to weigh in or am I good to merge?

You are good to merge!

2023-03-10 20:53 UTC, AARON-CLARK commented
> LGTM! @AARON-CLARK do you want anyone else to weigh in or am I good to merge?

You are good to merge!

2023-03-10 21:00 UTC, merged